url: http://zenorocha.github.io
baseurl: /dracula-theme

name: Dracula
description: 'A dark theme for Atom, Alfred, iTerm, Sublime Text, Textmate, Terminal.app, Vim, Xcode, and Zsh'

author: Zeno Rocha
author-url: 'http://zenorocha.com'

github-user: 'zenorocha'
github-repo: 'dracula-theme'